### ISSUE TITLE
Update to PureScript 0.13.0

### ISSUE THREAD

**Issue by JordanMartinez** [hdgarrood/purescript-benchotron#21]
Not sure when you'll get to this, but there are two problems stopping this from compiling in th enew release:
- use of an illegal escape code: `\ESC`
- outdated dependencies.

The second one isn't hard to fix, but I'm not familiar enough with the first one. Would it require Javascript FFI to something like `exports.escapeCode = "\ESC"`?

This issue affects how I'll update my learning repository to PureScript 0.13.0

**Comment by hdgarrood** [comment]
No, JS FFI is never necessary to put control characters in string literals in purescript. \ESC in Haskell means U+001B so it just needs to be changed to \x1B. (Until 0.13.0, purescript used the same escape codes as Haskell)
