### ISSUE TITLE
handleBenchmarkEXCEPTION

### ISSUE THREAD

**Issue by jutaro** [hdgarrood/purescript-benchotron#4]
is written handleBenchmarkException in the .js file, which results in an error for me:

### Benchmark: Finding the sum of two vectors ###
Started at: 00:16:58
Running... n=1000 (1/5)
/home/jutaro/Develop/purescript-vector/tmp/benchmarks.js:4141
                        return $foreign.handleBenchmarkEXCEPTION(name)(_498.va
                                        ^
TypeError: Object #<Object> has no method 'handleBenchmarkEXCEPTION'
    at /home/jutaro/Develop/purescript-vector/tmp/benchmarks.js:4141:41

**Comment by hdgarrood** [comment]
Thanks, fixed.
